spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: yinchaxian
    password: yinchaxian
    url: jdbc:mariadb://139.9.115.219:3306/BookShop?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  application:
    name: BookShop

mybatis:
  typeAliasesPackage: com.yinchaxian.bookshop.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  file:
    path: classpath:/log
    name: shop.log