spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: yinchaxian
    password: yinchaxian
    url: jdbc:mariadb://139.9.115.219:3306/BookShop?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  application:
    name: BookShop

mybatis:
  typeAliasesPackage: com.yinchaxian.bookshop.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /home/yinchaxian/bookshop/tomcat_log
      rotate: true
      pattern: '%t %a %A %m %U%q %s %D %I %B'
      buffered: true
      file-date-format: yyyy-MM-dd
      request-attributes-enabled: false
      rename-on-rotate: false

#logging:
#  file:
#    path: classpath:/log
#    name: shop.log

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql



